// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CustomerCare {
	
	
	public partial class Tipificaciones {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected Telerik.Web.UI.RadSkinManager rsmTipi;
		
		protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
		
		protected Telerik.Web.UI.RadAjaxLoadingPanel RadAjaxLoadingPanel1;
		
		protected Telerik.Web.UI.RadAjaxPanel RadAjaxPanel1;
		
		protected Telerik.Web.UI.RadTreeList RadTreeList1;
	}
}
